name: 雷神自动停止加速

on:
  push:
  schedule:
    # 每天北京时间 2:00 执行（UTC时间 18:00）
    - cron: '00 18 * * *'
  workflow_dispatch:  # ✅ 添加这行，支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: "雷神加速器暂停脚本"
        run: |
          node main.js
        env:
          LEISHEN_USERNAME: ${{ secrets.LEISHEN_USERNAME }}
          LEISHEN_PASSWORD: ${{ secrets.LEISHEN_PASSWORD }}
